info:
  app:
    name: api-bank
    description: bank financial transactions simulator
    version: v0.0.1

server:
  port: 8082

spring:
  data:
    mongodb:
      database: bank
      uri: mongodb://root:passw0rd@localhost:27017/bank