info:
  app:
    name: api-bank
    description: bank financial transactions simulator
    version: v0.0.1

server:
  port: 4200

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bank
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect