info:
  app:
    name: api-bank
    description: bank financial transactions simulator
    version: v0.0.1

server.port: 8081

spring:
  data:
    mongodb:
      database: bank
      uri: mongodb://root:Apoio2019!@localhost:27017

#      profiles:
#        active: integration
#        devtools:
#          restart:
#            enabled: true
#          livereload:
#            enabled: true


