INSERT INTO CLIENT ( ID, NAME, MAIL, CLIENT_TYPE) VALUES ( 1, 'Jessika', 'jessika@teste.com.br', '0');
INSERT INTO BANK_ACCOUNT ( ID, ACCOUNT_NUMBER, BALANCE, STATUS, CLIENT_ID) VALUES ( 1, 123456, 3000, 0, 1);
INSERT INTO BANK_ACCOUNT ( ID, ACCOUNT_NUMBER, BALANCE, STATUS, CLIENT_ID) VALUES ( 2, 123789, 3599, 0, 1);

INSERT INTO CLIENT ( ID, NAME, MAIL, CLIENT_TYPE) VALUES ( 2, 'Guilherme', 'guilherme@teste.com.br', '0');
INSERT INTO BANK_ACCOUNT ( ID, ACCOUNT_NUMBER, BALANCE, STATUS, CLIENT_ID) VALUES ( 3, 654321, 5000, 0, 2);
