INSERT INTO CLIENT ( ID, NAME, MAIL, CLIENT_TYPE) VALUES ( 1, 'Jéssika', 'jessika@teste.com.br', '0');
INSERT INTO BANK_ACCOUNT ( ID, ACCOUNT_NUMBER, BALANCE, CLIENT_ID) VALUES ( 1, 123456, 3000, 1);
INSERT INTO BANK_ACCOUNT ( ID, ACCOUNT_NUMBER, BALANCE, CLIENT_ID) VALUES ( 2, 123789, 3599, 1);