swagger: "2.0"
info:
  description: "Simulate the main financial transactions of a banking institution."
  version: "1.0.0"
  title: "API Bank Transactions"
  contact:
    email: "jessika.fernandes@dbserver.com.br"
host: "localhost:4200"


tags:
  - name: "client"
    description: "For a given client, it returns the customer's personal data and account."
  - name: "account"
    description: "Returns bank account details."
  - name: "admin"
    description: "Clients list and overall balance"

schemes:
  - "https"
  - "http"

definitions:

  Client:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: string
      mail:
        type: string
      clientType:
        type: string
        enum:
          - PF
          - PJ

  BankAccount:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      accountNumber:
        type: "integer"
        format: "int64"
      balance:
        type: number
        format: "double"
      status:
        type: string
        enum:
          - ACTIVE
          - BLOCKED

  Extract:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      accountNumber:
        type: "integer"
        format: "int64"
      dateTime:
        type: string
        format: "date"
      typeTransaction:
        type: string
        enum:
          - CRIACAO
          - BLOQUEIO
          - CONSULTA
          - SAQUE
          - DEPOSITO
          - TRANSFERENCIA
      balance:
        type: number
        format: "double"
      status:
        type: string
        enum:
          - ACTIVE
          - BLOCKED
      accountTransfer:
        type: "integer"
        format: "int64"
      valueTransfer:
        type: number
        format: "double"